language: generic

dotnet: 1.0.1

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: osx # OSX 10.11
      osx_image: xcode7.2
  allow_failures:
    - os: osx

script:
  - dotnet --info
  # Run build
  - echo 'dotnet restore' && echo -en 'travis_fold:start:dotnet_restore'
  - dotnet restore -v n
  - echo -en 'travis_fold:end:dotnet_restore'
  - dotnet build -v n
